; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : EngineTestSong
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env3,@env6,@env0 ; 00 : Main
	.word @env5,@env3,@env6,@env0 ; 01 : NoiseDrum
	.word @env7,@env3,@env6,@env0 ; 02 : NoiseDrumHi
	.word @env4,@env3,@env6,@env0 ; 03 : TriangleBassIntro
	.word @env1,@env3,@env6,@env0 ; 04 : TriangleBassMain

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c3,$7f,$00,$02
@env2:
	.byte $00,$ce,$ce,$cd,$cb,$ca,$c9,$c7,$c5,$c4,$c3,$c1,$00,$0b
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $00,$cc,$ca,$c8,$00,$03
@env5:
	.byte $00,$c8,$c4,$c1,$00,$03
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $00,$ce,$cc,$ca,$c8,$c5,$c2,$c0,$00,$07

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $f5, $47, $ff, $f5
@song0ref10:
	.byte $47, $80, $25, $9d, $27, $9b, $25, $9b, $29, $9d, $25, $9b, $27, $9b, $25, $bb, $47, $88, $2a, $9d, $29, $9b, $27, $9b
	.byte $25, $9d, $27, $9b, $29, $9b, $2c, $9d, $2c, $9b
	.byte $41, $1e
	.word @song0ref10
	.byte $41, $1e
	.word @song0ref10
	.byte $41, $1e
	.word @song0ref10
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref57:
	.byte $ff, $f5, $ff, $f5, $ff, $f5, $ff, $f5, $ff, $f5
	.byte $41, $0a
	.word @song0ref57
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $f5, $86, $4f, $fb, $2e, $33, $bb, $4f, $fc, $30, $35, $bb, $4f, $fc, $31, $36, $b9, $4f, $fb, $33, $3a, $bb, $88
@song0ref98:
	.byte $1f, $9d, $25, $9b, $1f, $9b, $25, $9d, $1f, $9b, $25, $9b, $1f, $9d, $25, $9b
	.byte $41, $10
	.word @song0ref98
	.byte $41, $10
	.word @song0ref98
	.byte $41, $10
	.word @song0ref98
	.byte $41, $10
	.word @song0ref98
	.byte $41, $10
	.word @song0ref98
	.byte $41, $10
	.word @song0ref98
	.byte $41, $10
	.word @song0ref98
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref139:
	.byte $82, $1f, $8d, $00, $8d, $1f, $8b, $00, $8d, $84, $22, $8d, $00, $ab, $82, $1f, $8b, $00, $8d, $1f, $8d, $00, $8b, $84
	.byte $22, $8d, $00, $ab
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $41, $18
	.word @song0ref139
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0a
	.word @song0ref57
	.byte $41, $0a
	.word @song0ref57
	.byte $42
	.word @song0ch4loop
